//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APL.BL.SFTS.DataBridgeZone
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EDMx_Connection : DbContext
    {
        public EDMx_Connection()
            : base("name=EDMx_Connection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RSO> RSOes { get; set; }
        public virtual DbSet<RSO_APP_PASSWORD> RSO_APP_PASSWORD { get; set; }
    }
}
