//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APL.BL.SFTS.DataBridgeZone
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSO
    {
        public decimal ID { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> DISTRIBUTOR { get; set; }
        public string NAME { get; set; }
        public string MOBILE { get; set; }
        public string HANDSET_MOBILE { get; set; }
    
        public virtual RSO_APP_PASSWORD RSO_APP_PASSWORD { get; set; }
    }
}
