//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APL.BL.SFTS.DataBridgeZone
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSO_APP_PASSWORD
    {
        public decimal RSOID { get; set; }
        public string PASSWORD { get; set; }
        public string LOGINNAME { get; set; }
    
        public virtual RSO RSO { get; set; }
    }
}
